apiVersion: v1
kind: Service
metadata:
  labels:
    app: weevs
    env: staging
    tier: api
  name: dev-weevs-api
  namespace: staging
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: weevs
    env: staging
    tier: api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: NodePort